// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsSUuFvb3y9Q6kOMrjI4f8mKpDS5nCY7I',
    appId: '1:981787185283:web:18bd63145a1aa9480d0bb6',
    messagingSenderId: '981787185283',
    projectId: 'insabhi-icon-office',
    authDomain: 'insabhi-icon-office.firebaseapp.com',
    storageBucket: 'insabhi-icon-office.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlSSMMvxLdF23iV-EvZhBh42EVlZlfgNU',
    appId: '1:981787185283:android:e66e2f574006a2050d0bb6',
    messagingSenderId: '981787185283',
    projectId: 'insabhi-icon-office',
    storageBucket: 'insabhi-icon-office.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfO1jZb93dUpOzBxt2BOEDsWVGcNoi4r4',
    appId: '1:981787185283:ios:610f33b22a841b9d0d0bb6',
    messagingSenderId: '981787185283',
    projectId: 'insabhi-icon-office',
    storageBucket: 'insabhi-icon-office.firebasestorage.app',
    iosBundleId: 'com.example.insabhiIconOffice',
  );
}
